import {
  ChallengesApp,
  Counter1,
  Counter2,
  DrumKit,
  ElegantContext,
  EventsApp,
  Forkify,
  GuessMyNumber,
  InvestmentCalculator,
  MystiqueQuiz,
  PlacePicker,
  Quiz,
  RandomColorGenerator,
  RandomPasswordGenerator,
  ReactEssentials,
  TaskManager,
  TicTacToe,
  TimerGame,
} from "@/assets";

export default [
  {
    title: "Forkify",
    imageUrl: Forkify,
    liveUrl: "https://forkify-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Forkfiy",
  },
  {
    title: "Challenges App",
    imageUrl: ChallengesApp,
    liveUrl: "https://challenges-app-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Challenges-App",
  },
  {
    title: "Counter 1",
    imageUrl: Counter1,
    liveUrl: "https://number-counter-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Number-Counter",
  },
  {
    title: "Counter 2",
    imageUrl: Counter2,
    liveUrl: "https://counter-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Counter",
  },
  {
    title: "Drum Kit",
    imageUrl: DrumKit,
    liveUrl: "https://drum-kit-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Drum-Kit",
  },
  {
    title: "Elegant Context",
    imageUrl: ElegantContext,
    liveUrl: "https://elegant-context.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Elegant-Context",
  },
  {
    title: "React Events",
    imageUrl: EventsApp,
    liveUrl: "",
    githubUrl: "https://github.com/Anujshivhare/React-Events",
  },
  {
    title: "Guess My Number",
    imageUrl: GuessMyNumber,
    liveUrl: "https://guess-my-number-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Guess-My-Number",
  },
  {
    title: "Investment Calculator",
    imageUrl: InvestmentCalculator,
    liveUrl: "https://investment-calculator-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Investment-Calculator",
  },
  {
    title: "Mystique Quiz",
    imageUrl: MystiqueQuiz,
    liveUrl: "https://mystique-quiz.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Mystique-Quiz",
  },
  {
    title: "Place Picker",
    imageUrl: PlacePicker,
    liveUrl: "https://place-picker-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Place-Picker",
  },
  {
    title: "Quiz Game",
    imageUrl: Quiz,
    liveUrl: "https://quiz-game-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Quiz",
  },
  {
    title: "Random Color Generator",
    imageUrl: RandomColorGenerator,
    liveUrl: "https://random-color-generator-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Random-Color-Generator",
  },
  {
    title: "Random Password Generator",
    imageUrl: RandomPasswordGenerator,
    liveUrl: "https://random-password-generator-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Random-Password-Generator",
  },
  {
    title: "React Essentials",
    imageUrl: ReactEssentials,
    liveUrl: "https://react-essentials-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/React-Essentials",
  },
  {
    title: "Task Manager",
    imageUrl: TaskManager,
    liveUrl: "https://task-manager-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Task-Manager",
  },
  {
    title: "Tic-Tac-Toe",
    imageUrl: TicTacToe,
    liveUrl: "https://tic-tac-toe-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Tic-Tac-Toe",
  },
  {
    title: "Timer Game",
    imageUrl: TimerGame,
    liveUrl: "https://timer-game-in-reactjs.netlify.app/",
    githubUrl: "https://github.com/Anujshivhare/Timer-Game",
  },
];
